openapi: 3.0.0
info:
  title: Generic's Pizza Rest API
  description: This is the Rest API that is used by Generic's Pizza Apps.
  version: 0.0.1
paths:
  /menu:
    get:
      summary: Returns a list of all menu items.
      responses:
        '200':
          description: A JSON array of menu items
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/MenuItem'
    post:
      summary: Create a new menu item.
      responses:
        '200':
          description: The newly created menu item.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/MenuItem'
  /menu/{id}:
    delete:
      summary: Delete a menu item.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the menu item.
      responses:
        '200':
          description: Item was successfully deleted.
  /menu/{id}/image:
    get:
      summary: Get the menu item image.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the menu item.
      responses:
        '200':
          description: Image bytes
    post:
      summary: Add a menu item image.
      responses:
        '200':
          description: Ok
    delete:
      summary: Delete the menu item image.
      responses:
        '200':
          description: Ok
  /order:
    post:
      summary: Create a new order
      responses:
        '200':
          description: Ok
  /order/check_price:
    post:
      summary: Get the estimated order price.
      responses:
        '200':
          description: Ok
  /order/check_location:
    post:
      summary: Get the location of the restaurant.
      responses:
        '200':
          description: Ok
  /order/current:
    get:
      summary: Get the current orders.
      responses:
        '200':
          description: Ok
  /order/history:
    get:
      summary: Get the orders history.
      responses:
        '200':
          description: Ok
  /auth/user:
    post:
      summary: Create a new account.
      responses:
        '200':
          description: Ok
    get:
      summary: Get info about current user.
      responses:
        '200':
          description: Ok
  /auth/login:
    post:
      summary: Login.
      responses:
        '200':
          description: Ok
  /auth/signout:
    post:
      summary: Sign out.
      responses:
        '200':
          description: Ok
  /user:
    get:
      summary: Get all existign users.
      responses:
        '200':
          description: Ok
  /user/{id}:
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the user.
      summary: Detele the user.
      responses:
        '200':
          description: Ok
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the user.
      summary: Update the user.
      responses:
        '200':
          description: Ok
components:
  schemas:
    MenuItem:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        price:
          type: integer
      