disabled_rules:
  - identifier_name

custom_rules:
  model_inheritance_name_ends_with_entry:
    name: "Database models names scheme"
    regex: "(?<!Entry)(: Model)"
    message: "Class names representing database models should end with 'Entry'"