disabled_rules:
  - identifier_name
  - line_length
  - comment_spacing
  - private_over_fileprivate
  - todo

custom_rules:
  use_custom_text_field:
    name: "Use custom text field"
    regex: "UITextField"
    message: "Do not use 'UITextField', use 'TextField' from 'GenericsUIKit' instead"
