name: Unit tests

on: 
  workflow_dispatch

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        cd generics-ios-app
        xcodebuild test -project GenericsApp.xcodeproj -scheme GenericsApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 mini,OS=17.0.1' -testPlan NoServerTests | xcpretty && exit ${PIPESTATUS[0]}