name: Unit tests

on: 
  workflow_dispatch

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        xcodebuild test -workspace shared-workspace.xcworkspace -scheme GenericsApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0.1' -testPlan NoServerTests | xcpretty && exit ${PIPESTATUS[0]}